# Exact multiple sequence alignment with bounding.

![Description](Subject.png)

In [11]:
import numpy as np
from Bio.PDB import *
from Bio.Seq import Seq
import shutil
import warnings
import requests
import os
import pandas as pd
from itertools import product 
from Bio.PDB.PDBExceptions import PDBConstructionWarning
from Bio.PDB.DSSP import DSSP
from Bio import SeqIO
warnings.simplefilter('ignore', PDBConstructionWarning)

### Similarity Matrix

In [4]:
def load_blosum(filename):
    """
    Load a substitution matrix (e.g. BLOSUM) from a file.

    Returns:
        dict: {(aa1, aa2): score}
    """
    matrix = {}

    with open(filename) as f:
        lines = f.readlines()

    # Ignore comments
    lines = [line.strip() for line in lines if line.strip() and not line.startswith("#")]

    # First non-comment line = column headers
    headers = lines[0].split()

    # Remaining lines = rows
    for line in lines[1:]:
        parts = line.split()
        row_aa = parts[0]
        scores = parts[1:]

        for col_aa, score in zip(headers, scores):
            matrix[(row_aa, col_aa)] = int(score)

    return matrix

blosum = load_blosum("BLOSUM62.txt")

### Gap Parameters

In [5]:
gap = -4
gap_open = -11
gap_ext = -1

### Needleman-Wunsh algorithm for any MSA of K input sequences

Similarity column vs column

In [6]:
def score_column_vs_column(colA, colB, blosum, gap):
    total = 0
    count = 0

    for a in colA:
        for b in colB:
            # cas gap-gap
            if a == '-' and b == '-':
                continue

            # cas gap-aa
            if a == '-' or b == '-':
                total += gap
                count += 1
                continue

            # cas aa-aa
            if (a, b) in blosum:
                total += blosum[(a, b)]
            else:
                total += blosum[(b, a)]

            count += 1

    return total / count if count > 0 else 0.0


In [7]:
# Needleman-wunsh bloc-bloc affine

def needleman_wunsch_align_vs_align_affine(align1, align2, blosum, gap_open, gap_ext, gap_char="-"):
    n1, l1 = align1.shape
    n2, l2 = align2.shape
    NEG = -1e18

    # M: diag ; X: up (gap in align2) ; Y: left (gap in align1)
    matrix = np.full((l1+1, l2+1), NEG, dtype=float)
    X = np.full((l1+1, l2+1), NEG, dtype=float)
    Y = np.full((l1+1, l2+1), NEG, dtype=float)

    backtracking_matrix = np.full((l1+1, l2+1), -1, dtype=np.int8)  # prev state 0/1/2
    btX = np.full((l1+1, l2+1), -1, dtype=np.int8)
    btY = np.full((l1+1, l2+1), -1, dtype=np.int8)

    matrix[0,0] = 0.0
    backtracking_matrix[0,0] = 0
    # 1 = horiz ; 2 = vert ; 3 = diag

    # ---- CONSTRUCTION MATRICES ----
    # init first column (only X)
    for i in range(1, l1+1):
        if i == 1:
            X[i,0] = matrix[i-1,0] + gap_open + gap_ext
            btX[i,0] = 0
        else:
            X[i,0] = X[i-1,0] + gap_ext
            btX[i,0] = 1
            matrix[i,0] = NEG

    # init first row (only Y)
    for j in range(1, l2+1):
        if j == 1:
            Y[0,j] = matrix[0,j-1] + gap_open + gap_ext
            btY[0,j] = 0
        else:
            Y[0,j] = Y[0,j-1] + gap_ext
            btY[0,j] = 2
            matrix[0,j] = NEG


    for i in range(1,l1+1):
        for j in range(1,l2+1):                
            # X (up): either open from M or extend X
            open_x = matrix[i-1,j] + gap_open + gap_ext
            ext_x  = X[i-1,j] + gap_ext
            if open_x >= ext_x:
                X[i,j] = open_x
                btX[i,j] = 0
            else:
                X[i,j] = ext_x
                btX[i,j] = 1

            # Y (left): open from M or extend Y
            open_y = matrix[i,j-1] + gap_open + gap_ext
            ext_y  = Y[i,j-1] + gap_ext
            if open_y >= ext_y:
                Y[i,j] = open_y
                btY[i,j] = 0
            else:
                Y[i,j] = ext_y
                btY[i,j] = 2

            # M (diag): come from best previous state + column score
            s = score_column_vs_column(align1[:, i-1], align2[:, j-1], blosum, 0) #modifier score pour pas compter les gap 2 fois
            prev = [matrix[i-1,j-1], X[i-1,j-1], Y[i-1,j-1]]
            p = int(np.argmax(prev))
            matrix[i,j] = prev[p] + s
            backtracking_matrix[i,j] = p


    # choose best ending state
    i, j = l1, l2
    end = [matrix[i,j], X[i,j], Y[i,j]]
    state = int(np.argmax(end))
    score = end[state]

    # ---- BACKTRACKING ----
    cols1 = []
    cols2 = []

    i, j = l1, l2
    while i > 0 or j > 0:
        if state == 0:  # M: diag
            prev = backtracking_matrix[i,j]
            cols1.append(align1[:, i-1])
            cols2.append(align2[:, j-1])
            i -= 1; j -= 1
            state = int(prev)
        elif state == 1:  # X: up (gap in align2)
            prev = btX[i,j]
            cols1.append(align1[:, i-1])
            cols2.append(np.array([gap_char]*n2))
            i -= 1
            state = int(prev)
        else:  # Y: left (gap in align1)
            prev = btY[i,j]
            cols1.append(np.array([gap_char]*n1))
            cols2.append(align2[:, j-1])
            j -= 1
            state = int(prev)

    cols1.reverse()
    cols2.reverse()

    new1 = np.stack(cols1, axis=1)  # (n1, L)
    new2 = np.stack(cols2, axis=1)  # (n2, L)
    final_align = np.vstack([new1, new2])  # (n1+n2, L)     

    return new1, new2, matrix, score, final_align

In [8]:
#TEST ALIGN VS ALIGN AFFINE
print("========== TEST ALIGN VS ALIGN AFFINE ======")
align1 = np.array([
    list("CHAT"),
    list("C-AT")])

align2 = np.array([
    list("BAT"),
    list("CAT")])

new_align1, new_align2 , M, score, final_align = needleman_wunsch_align_vs_align_affine(align1, align2, blosum, gap_open, gap_ext, gap_char='-')

print("score:", score)
print(M)
print("new align:")
for row in final_align:
    print("".join(row))

========== TEST ALIGN VS ALIGN AFFINE ======
score: 0.0
[[ 0.000e+00 -1.000e+18 -1.000e+18 -1.000e+18]
 [-1.000e+18  3.000e+00 -1.200e+01 -1.400e+01]
 [-1.000e+18 -1.275e+01  2.000e+00 -1.000e+01]
 [-1.000e+18 -1.400e+01 -5.000e+00  2.000e+00]
 [-1.000e+18 -1.500e+01 -1.000e+01  0.000e+00]]
new align:
CHAT
C-AT
B-AT
C-AT


In [9]:
def column_score(column, blosum, gap) -> float:
	total = 0
	K = len(column)

	for k in range(K):
		for j in range(k+1, K):
			a = column[k]
			b = column[j]
			
			# cas gap-gap
			if a == '-' and b == '-':
				continue
			
			# cas gap-aa
			if a == '-' or b == '-':
				total += gap
				continue

			# cas aa-aa
			if (a, b) in blosum:
				total += blosum[(a, b)]
			else:
				total += blosum[(b, a)]

	return total

In [12]:
def K_maximum_similarity(sequences, blosum, gap):
	K = len(sequences)
	dimensions = np.array([len(seq) + 1 for seq in sequences])
	ranges = [range(d) for d in dimensions]
	S = np.zeros(dimensions, dtype=float)
	best_decisions = np.zeros(dimensions, dtype=int)  # to store the best state for backtracking
	
	# Initialization of S 
	
	S[tuple([0]*K)] = 0.0
	
	for idx in product(*ranges):
		# There are exactly 2^K - 1 possible previous states
		# We can represent each state as a K-bit binary number, where bit i is 1 if we take the character from sequence i, and 0 if we take a gap in sequence i.
		
		if idx == tuple([0]*K):
			continue
		max_score = -1e18
		best_state = None
		for state in range(1, 2**K):
			prev_idx = list(idx)
			score = 0.0
			valid = True
			column = []
			
			for i in range(K):
				if (state >> i) & 1: # we take a character from sequence i
					prev_idx[i] -= 1
					if prev_idx[i] < 0:
						valid = False
						break
					column.append(sequences[i][prev_idx[i]])  # gap column will be scored against this character
				else:  # it is a jump in sequence i
					column.append('-')
			
			if not valid:
				continue

			score = column_score(column, blosum, gap) + S[tuple(prev_idx)]

			if score > max_score:
				max_score = score
				best_state = state
		
		S[idx] = max_score
		best_decisions[idx] = best_state

	# Backtracking to reconstruct the alignment

	# First compute the length of the final alignment (number of columns)
	length = 0
	idx = tuple(dimensions - np.array([1]*K))  # start from the end
	while idx != tuple([0]*K):
		state = best_decisions[idx]
		length += 1
		for i in range(K):
			if (state >> i) & 1:  # we took a character from sequence i
				idx = list(idx)
				idx[i] -= 1
				idx = tuple(idx)


	alignement = np.array([['']*(length) for i in range(K)], dtype=object)
	idx = tuple(dimensions - np.array([1]*K))  # start from the end
	idx_alignment = length-1
	while idx != tuple([0]*K):
		state = best_decisions[idx]
		for i in range(K):
			if (state >> i) & 1:  # we took a character from sequence i
				alignement[i][idx_alignment] = sequences[i][idx[i]-1]
				idx = list(idx)
				idx[i] -= 1
				idx = tuple(idx)
			else:  # we took a gap in sequence i
				alignement[i][idx_alignment] = '-'
		idx_alignment -= 1


	return float(S[tuple(dimensions - np.array([1]*K))]), S, alignement

In [13]:
def score(pair):
	a, b = pair
	if a == '-' and b == '-':
		return ValueError("Invalid pair: both characters cannot be gaps")
	elif a == '-' or b == '-':
		return -2
	else:
		return 0 if a == b else -3



In [14]:
# ====== TEST MSA ======

blosum = {pair: score(pair) for pair in product("ARNDCQEGHILKMFPSTWYVBZX.", repeat=2)}
gap = -2

similarity, S_matrix, alignment = K_maximum_similarity(["ACCCGAG", "ACTACC", "TCCTACGG"], blosum, gap)
print("similarity:", similarity)
print("S matrix:")
print(S_matrix)
print("alignment:")
for row in alignment:
	print("".join(row))

similarity: -32.0
S matrix:
[[[  0.  -4.  -8. -12. -16. -20. -24. -28. -32.]
  [ -4.  -7. -11. -15. -19. -20. -24. -28. -32.]
  [ -8. -11. -11. -15. -19. -23. -24. -28. -32.]
  [-12. -12. -15. -18. -19. -23. -27. -31. -35.]
  [-16. -16. -19. -22. -23. -23. -27. -31. -35.]
  [-20. -20. -20. -23. -27. -27. -27. -31. -35.]
  [-24. -24. -24. -24. -28. -31. -31. -34. -38.]]

 [[ -4.  -7. -11. -15. -19. -20. -24. -28. -32.]
  [ -4.  -6. -10. -14. -18. -16. -20. -24. -28.]
  [ -8. -10. -10. -14. -18. -20. -20. -24. -28.]
  [-12. -12. -14. -17. -18. -22. -24. -27. -31.]
  [-16. -16. -18. -21. -22. -19. -23. -27. -31.]
  [-20. -20. -20. -22. -26. -23. -23. -27. -31.]
  [-24. -24. -24. -24. -28. -27. -27. -30. -34.]]

 [[ -8. -11. -11. -15. -19. -23. -24. -28. -32.]
  [ -8. -10. -10. -14. -18. -20. -20. -24. -28.]
  [ -8. -10.  -6. -10. -14. -18. -16. -20. -24.]
  [-12. -12. -10. -13. -14. -18. -20. -23. -27.]
  [-16. -16. -14. -17. -18. -18. -22. -26. -30.]
  [-20. -20. -16. -18. -22. -22. -19.

# Carillo Lipman

In [15]:
def pairwise_alignment_scores(sequences, blosum, gap):
	K = len(sequences)
	max_len = max(len(seq) for seq in sequences)
	S = np.zeros((K, K, max_len+1, max_len+1), dtype=float)

	for k in range(K):
		for l in range(k+1, K):
			seqA = sequences[k][::-1]
			seqB = sequences[l][::-1]
			_, similarity_matrix, _ = K_maximum_similarity(np.array([seqA, seqB]), blosum, gap)
			for i in range(len(seqA)+1):
				for j in range(len(seqB)+1):
					S[k, l, i, j] = similarity_matrix[len(seqA)-i, len(seqB)-j]
					S[l, k, j, i] = similarity_matrix[len(seqA)-i, len(seqB)-j]
	return S


In [16]:
def similarity_upper_bound(sequences, blosum, gap):
	K = len(sequences)
	S = pairwise_alignment_scores(sequences, blosum, gap)
	bound = 0.0
	for i in range(K):
		for j in range(i+1, K):
			bound += S[i, j, 0, 0]
	return bound


In [17]:
pairwise_alignment_scores(["CHAT", "CAT","ANANAS"], blosum, gap)

array([[[[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.]],

        [[ -2.,  -4.,  -6.,  -8.,   0.,   0.,   0.],
         [ -3.,  -2.,  -4.,  -6.,   0.,   0.,   0.],
         [ -2.,   0.,  -2.,  -4.,   0.,   0.,   0.],
         [ -4.,  -2.,   0.,  -2.,   0.,   0.,   0.],
         [ -6.,  -4.,  -2.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.]],

        [[-13., -11.,  -9.,  -8.,  -7.,  -9.,  -8.],
         [-12., -10.,  -8.,  -6.,  -5.,  -7.,  -6.],
         [-11.,  -9.,  -7.,  -5.,  -3.,  -5.,  -4.],
         [-13., -11.,  -9.,  -7.,  -5.,  -3.,  -2.],
         [-12., -10.,  -8.,  -6.,  -4.,  -

In [18]:
similarity_upper_bound(["CHAT", "CAT","ANANAS"], blosum, gap)

np.float64(-27.0)

In [19]:
def neighbors(state, comp):
	# state is a tuple of indices (i1, i2, ..., iK)
	# we want to return all states that can come after this state by taking at least one character from the sequences (no all-gap columns)
	K = len(state)
	neighbors = []
	for s in range(1, 2**K):  # from 1 to 2^K - 1
		next_state = list(state)
		valid = True
		for i in range(K):
			if (s >> i) & 1:  # we take a character from sequence i
				next_state[i] += 1
		if not comp[tuple(next_state)]:
			neighbors.append(tuple(next_state))
	return neighbors

def carillo_lipman_MSA(sequences, blosum, gap, limit):
	K = len(sequences)
	dimensions = np.array([len(seq) + 1 for seq in sequences])
	ranges = [range(d) for d in dimensions]
	S = np.zeros(dimensions, dtype=float)
	computed = np.zeros(dimensions, dtype=bool)  # to track which states have been computed or are useless
	best_decisions = np.zeros(dimensions, dtype=int)  # to store the best state for backtracking
	
	# Initialization of S 
	
	S[tuple([0]*K)] = 0.0
	
	to_compute = neighbors(tuple([0]*K), computed)

	while to_compute:
		idx = to_compute.pop(0)
		computed[idx] = True
		
		max_score = -1e18
		best_state = None
		for state in range(1, 2**K):
			prev_idx = list(idx)
			score = 0.0
			valid = True
			column = []
			
			for i in range(K):
				if (state >> i) & 1: # we take a character from sequence i
					prev_idx[i] -= 1
					if prev_idx[i] < 0:
						valid = False
						break
					column.append(sequences[i][prev_idx[i]])  # gap column will be scored against this character
				else:  # it is a jump in sequence i
					column.append('-')
			
			if not valid:
				continue

			score = column_score(column, blosum, gap) + S[tuple(prev_idx)]

			if score > max_score:
				max_score = score
				best_state = state
		if max_score < limit:
			S[idx] = -np.inf
			best_decisions[idx] = (-1)*K
		else:
			S[idx] = max_score
			best_decisions[idx] = best_state

	# Backtracking to reconstruct the alignment

	# First compute the length of the final alignment (number of columns)
	length = 0
	idx = tuple(dimensions - np.array([1]*K))  # start from the end
	while idx != tuple([0]*K):
		state = best_decisions[idx]
		length += 1
		for i in range(K):
			if (state >> i) & 1:  # we took a character from sequence i
				idx = list(idx)
				idx[i] -= 1
				idx = tuple(idx)


	alignement = np.array([['']*(length) for i in range(K)], dtype=object)
	idx = tuple(dimensions - np.array([1]*K))  # start from the end
	idx_alignment = length-1
	while idx != tuple([0]*K):
		state = best_decisions[idx]
		for i in range(K):
			if (state >> i) & 1:  # we took a character from sequence i
				alignement[i][idx_alignment] = sequences[i][idx[i]-1]
				idx = list(idx)
				idx[i] -= 1
				idx = tuple(idx)
			else:  # we took a gap in sequence i
				alignement[i][idx_alignment] = '-'
		idx_alignment -= 1


	return float(S[tuple(dimensions - np.array([1]*K))]), S, alignement

In [20]:
carillo_lipman_MSA(["ACCCGAG", "ACTACC", "TCCTACGG"], blosum, gap, limit=-5.0)

KeyboardInterrupt: 

## Performance evaluation

![Description](Performance_evaluation.png)